### ISSUE TITLE
ONLP Baseconf service failing on BF2556x

### ISSUE THREAD

**Issue by johntoomey** [NetworkGradeLinux/meta-mion-bsp#26]
[FAILED] Failed to start ONLP Baseconfig Initialisation.

i think this is the same error on both systems but with different causes

EDIT: looks like this error is only on the bf2556x

**Comment by johntoomey** [comment]
irq_debug.ko builds and installs. loads when insmod/modprobe by hand but errors when installed by the baseconf service... no idea why..

**Comment by CommitThis** [comment]
Looks like it may be looking for the kmod and not finding it? Check that the kmod is in the directories that were dumped?

**Comment by johntoomey** [comment]
fixed with the following commits: 
- https://github.com/NetworkGradeLinux/meta-mion/commit/2d6c994a1fe5687faa62a87040182e0c087eab71
- https://github.com/NetworkGradeLinux/meta-mion-bsp/commit/4c066c545abf4d1a9f5ebe41eb8b08e4b2b616e8
