### ISSUE TITLE
bf2556x-1t platform scripts not added to image

### ISSUE THREAD

**Issue by gerritavenant** [NetworkGradeLinux/meta-mion-bsp#37]
The platform scripts packaged in `platform-stordis-bf2556x-1t` does not get added to the image.
If I manually add it to my image using `IMAGE_INSTALL_append = "platform-stordis-bf2556x-1t"`, I can see it in the rootfs.

I'm building for bf2556x-1t using the command `../mc_build.sh -m stordis-bf2556x-1t -v stordis -h host-onie:mion-onie-image-onlpv1`.

I can see the platform package being referenced in the machine configuration file, so not complete sure why it is not included: 
https://github.com/NetworkGradeLinux/meta-mion-bsp/blob/30f2347cc59c3edaf4b08c77f8acfb836954a843/meta-mion-stordis/conf/machine/stordis-bf2556x-1t.conf#L30

**Comment by toganlabs** [comment]
This is a problem within do_install.
