### ISSUE TITLE
Boot issue on APS BF6064

### ISSUE THREAD

**Issue by johntoomey** [NetworkGradeLinux/meta-mion-bsp#47]
[FAILED] Failed to start Setup platform ag7648.
See 'systemctl status platform-stordis-bf6064x-t-init.service' for details.

**Comment by johntoomey** [comment]
Cannot get access to a working bf6064 to test - marking as blocked

**Comment by toganlabs** [comment]
I *think* I have this fixed however without access to the switch, I don't know.

**Comment by johntoomey** [comment]
@CommitThis commit this fix https://github.com/NetworkGradeLinux/meta-mion-bsp/pull/57 i think its all that needs to be done here but we will confirm with @toganlabs when she is available
