### ISSUE TITLE
Create ext4 images for qemu

### ISSUE THREAD

**Issue by kprosise** [NetworkGradeLinux/meta-mion-bsp#51]
As of commit  a7c543e, ext4 images are not created, which qemu was dependent on. Appending  ext4 to the FSIMAGE_TYPES for qemu images is likely the simplest approach, and should be very simple.

**Comment by kprosise** [comment]
[meta-mion PR #105](https://github.com/NetworkGradeLinux/meta-mion/pull/105) fixes/implements this, and currently pending. If merged, this issue can be closed

**Comment by kprosise** [comment]
PR mentioned above has been merged, closing issue.

**Comment by toganlabs** [comment]
https://github.com/NetworkGradeLinux/meta-mion/commit/51595b97b0e650d32bf583bf3f61d2a94e83f005
